In [1]:
from IPython.display import display
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
from sklearn.datasets import make_blobs
from inspect import signature as sig
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")

# < 나이브베이즈 알고리즘 (분류용 모델만 있음) >

1. GaussianNB

In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.naive_bayes import BernoulliNB, GaussianNB, MultinomialNB

In [3]:
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target)

In [13]:
cancer.data[0,:] 
# 속성의 값이 모두 연속형임을 알 수 있다. -> 가우시안NB 쓰기!

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [14]:
model = GaussianNB()
model.fit(X_train, y_train)
train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)
display(train_score, test_score)

0.9507042253521126

0.9300699300699301

2.  BernoulliNB

In [16]:
# random.randint() : [최저값, 최대값)의 범위에서 임의의 정수를 만듦

# [0, 2) 범위에서 다섯개의 임의의 정수를 생성합니다.
a = np.random.randint(2, size=5) 
print(a)

# [1, 5) 범위에서 (2, 3) 형태의 어레이를 생성합니다.
c = np.random.randint(1, 5, size=(2, 3))
print(c)

[0 0 1 1 0]
[[3 3 1]
 [3 2 4]]


In [22]:
X = np.random.randint(2, size=(100,100))
y = np.random.randint(4, size=100)
X_train, X_test, y_train, y_test = train_test_split(X, y)
model = BernoulliNB()
model.fit(X_train, y_train)
pred = model.predict(X_test)
print(pred)
model.score(X_test, y_test) # --> 당연히 점수는 형편없겠지...

[1 3 1 2 1 2 1 2 1 3 1 1 3 2 3 1 3 0 2 1 1 1 1 1 3]


0.24